import {createRequire} from 'node:module';
import {mkdir, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const output=fileURLToPath(new URL('../test-results/',import.meta.url));
await mkdir(output,{recursive:true});
const url=process.env.UI_URL || 'http://127.0.0.1:4310';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();
const errors=[]; const requests=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>requests.push({method:request.method(),url:request.url()}));
const checks=[];
const ok=message=>{checks.push(message);console.log('PASS '+message);};
try {
  await page.goto(url+'/admin/login');
  await page.getByText('인증 연결 전 · 실사용 비밀번호를 입력하지 마세요.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'로그인',exact:true}).isDisabled(),true);
  await page.screenshot({path:path.join(output,'login-desktop.png'),fullPage:true});ok('Login accurately shows unavailable authentication');
  await page.getByRole('link',{name:'화면 미리보기'}).click();
  await page.getByText('미리보기 모드입니다. 실제 계정 인증과 서버 업로드·자동 게시 기능은 연결 전입니다.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'준비 상태 확인'}).click();
  await page.getByText('제목을 입력하세요.',{exact:true}).waitFor();ok('Empty input reports missing fields');
  await page.getByRole('button',{name:'해시태그 추천',exact:true}).click();
  await page.getByText('제목 또는 설명을 먼저 입력하세요.',{exact:true}).waitFor();
  await page.locator('#title').fill('제주 해안, 하늘에서 담다');
  await page.locator('#description').fill('제주 해안의 곡선과 파도를 드론으로 기록했습니다.');
  await page.locator('#region').fill('제주');
  await page.locator('#shoot-type').selectOption({label:'드론촬영'});
  await page.getByRole('button',{name:'해시태그 추천',exact:true}).click();
  await page.getByRole('button',{name:'+ #항공촬영',exact:true}).click();
  await page.locator('#tag-input').fill('#제주드론 #SpyMedia #제주드론');
  await page.locator('#tag-input').press('Enter');
  assert.equal(await page.locator('#tag-list .tag-chip').count(),3);ok('Suggested and manual tags deduplicate');
  await page.locator('#tag-input').fill('<img src=x onerror=alert(1)>');await page.locator('#tag-input').press('Enter');
  assert.equal(await page.locator('#tag-list img').count(),0);for(let i=0;i<3;i++)await page.locator('#tag-list .tag-chip').last().getByRole('button').click();ok('User text never becomes HTML');
  const fixture=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=800;const c=canvas.getContext('2d');const g=c.createLinearGradient(0,0,0,800);g.addColorStop(0,'#a3d4e5');g.addColorStop(.48,'#248baa');g.addColorStop(1,'#0a4965');c.fillStyle=g;c.fillRect(0,0,1200,800);c.fillStyle='#cad4ad';c.beginPath();c.moveTo(0,310);c.bezierCurveTo(340,390,250,570,750,620);c.bezierCurveTo(970,650,1100,750,1200,800);c.lineTo(0,800);c.fill();c.strokeStyle='#fff8';c.lineWidth=14;c.beginPath();c.moveTo(0,310);c.bezierCurveTo(340,390,250,570,750,620);c.bezierCurveTo(970,650,1100,750,1200,800);c.stroke();return canvas.toDataURL('image/png').split(',')[1];});
  const imageBuffer=Buffer.from(fixture,'base64');await writeFile(path.join(output,'test-coast.png'),imageBuffer);
  await page.locator('#image-input').setInputFiles(path.join(output,'test-coast.png'));
  await page.locator('#preview-media img').waitFor();
  await page.waitForFunction(()=>document.querySelector('#preview-media img')?.naturalWidth===1200);
  assert.equal(await page.locator('#preview-media img').evaluate(img=>img.complete&&img.naturalWidth===1200),true);
  await page.locator('#image-input').setInputFiles(path.join(output,'test-coast.png'));
  assert.equal(await page.locator('#image-files .file-row').count(),1);ok('Image previews and duplicate file selection are safe');
  await page.getByRole('button',{name:'test-coast.png 삭제',exact:true}).click();
  assert.equal(await page.locator('#preview-media img').count(),0);
  await page.locator('#image-input').setInputFiles(path.join(output,'test-coast.png'));ok('Delete and select the same image again');
  await page.locator('#image-input').setInputFiles({name:'blocked.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});
  await page.getByText('blocked.svg: JPG, PNG 또는 WebP 이미지를 선택하세요.',{exact:true}).waitFor();
  assert.equal(await page.locator('#image-files .file-row').count(),1);ok('Unsupported files rejected without losing valid selection');
  await page.getByRole('button',{name:'test-coast.png 삭제',exact:true}).click();
  await page.locator('#image-input').setInputFiles(path.join(output,'test-coast.png'));
  await page.locator('#image-input').setInputFiles({name:'test-second.png',mimeType:'image/png',buffer:imageBuffer});
  await page.getByRole('button',{name:'다음 이미지',exact:true}).click();
  assert.equal(await page.locator('.image-count').textContent(),'2 / 2');
  await page.getByRole('button',{name:'test-second.png 삭제',exact:true}).click();ok('Multiple image navigation and deleting active image');
  // Browser-generated video fixture: process-only, never sent to a social platform.
  const videoBase64=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const ctx=c.getContext('2d');ctx.fillStyle='#177e9b';ctx.fillRect(0,0,320,180);const stream=c.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise(resolve=>recorder.onstop=resolve);recorder.start();await new Promise(resolve=>setTimeout(resolve,300));recorder.stop();await stopped;stream.getTracks().forEach(track=>track.stop());const bytes=new Uint8Array(await new Blob(chunks).arrayBuffer());return btoa(String.fromCharCode(...bytes));});
  const videoBuffer=Buffer.from(videoBase64,'base64');
  await page.locator('#video-input').setInputFiles({name:'test-drone.webm',mimeType:'video/webm',buffer:videoBuffer});
  await page.locator('#preview-media video').waitFor();
  await page.waitForFunction(()=>document.querySelector('#preview-media video')?.readyState>=1);
  await page.getByRole('button',{name:'영상 삭제',exact:true}).click();assert.equal(await page.locator('#preview-media video').count(),0);
  await page.locator('#video-input').setInputFiles({name:'test-drone.webm',mimeType:'video/webm',buffer:videoBuffer});ok('Video metadata, deletion and re-selection');
  for(const name of ['유튜브','X','블로그'])await page.getByRole('button',{name,exact:true}).click();
  assert.equal(await page.locator('.channel-card.selected').count(),5);
  for(const name of ['유튜브','인스타그램','X','페이스북','블로그']){await page.getByRole('tab',{name,exact:true}).click();assert.equal(await page.locator('#detail-name').textContent(),name);}
  await page.getByRole('button',{name:'원고 복사',exact:true}).click();
  const clipboard=await page.evaluate(()=>navigator.clipboard.readText());assert.match(clipboard,/제주 해안/);ok('Five channel previews and semi-automatic blog draft');
  await page.locator('#toast').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'준비 상태 확인'}).click();await page.getByText('로컬 미리보기 입력이 준비되었습니다.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'준비 상태 확인'}).click({clickCount:2});assert.equal(await page.locator('#draft-feedback strong').count(),1);ok('Repeated readiness checks do not duplicate actions');
  await page.getByRole('tab',{name:'인스타그램',exact:true}).click();await page.getByRole('button',{name:'이미지',exact:true}).click();
  await page.screenshot({path:path.join(output,'admin-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'admin-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);ok('390px mobile viewport has no horizontal overflow');
  for(let i=0;i<6;i++)await page.getByRole('button',{name:'X',exact:true}).click();assert.equal(await page.locator('.channel-card[data-channel=x]').getAttribute('aria-pressed'),'true');
  for(const name of ['유튜브','인스타그램','X','페이스북','블로그'])await page.getByRole('button',{name,exact:true}).click();
  await page.getByText('미리볼 채널을 선택하세요',{exact:true}).waitFor();ok('Rapid channel clicks and deselecting all channels');
  await page.setViewportSize({width:390,height:844});await page.goto(url+'/admin/login');await page.getByRole('link',{name:'화면 미리보기'}).waitFor();await page.screenshot({path:path.join(output,'login-mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  assert.equal(requests.some(r=>r.method!=='GET'||!(r.url.startsWith(url)||r.url.startsWith('blob:'+url))),false);ok('No console errors, uploads or external requests');
  await writeFile(path.join(output,'browser-results.json'),JSON.stringify({checks,errors,requests,screenshots:['login-desktop.png','admin-desktop.png','admin-mobile.png','login-mobile.png'],fixture:'synthetic local canvas image and video; no approved publication content'},null,2));
} finally {await browser.close();}
